### ISSUE TITLE
大哥~A3.1测试版忘了传到Curse了~

### ISSUE THREAD

**Issue by Itzamana** [EKE00372/EKMinimap#2]
主要是[https://www.curseforge.com/wow/addons/ekminimap](https://www.curseforge.com/wow/addons/ekminimap)上也没有这个项目的地址，还是希望优秀的插件能被更多人用到…

**Comment by EKE00372** [comment]
![image](https://user-images.githubusercontent.com/1412472/99466995-66a78100-2978-11eb-9075-9c87ac21b0fc.png)

**Comment by Itzamana** [comment]
![](https://i.imgur.com/xFoxgp3.png)
啊这…
不过点开View All之后就能看到了…不好意思…
